### ISSUE TITLE
Typo in the v19 OSMC blog post

### ISSUE THREAD

**Issue by strugee** [osmc/website#5]
There's a typo in https://osmc.tv/2021/08/osmcs-august-update-is-here-with-kodi-v19/ (well, two): `3D MVC framepacked playback; HDR10+ suppor,` should be `3D MVC framepacked playback, HDR10+ support,`. (`s/;/,/` and a missing `t`.) Would've sent a PR but it looks like the blog is just a server-side app and not version-controlled?

Cheers <3

**Comment by samnazarko** [comment]
Fixed, thanks!
