### ISSUE TITLE
https://www.osmc.tv/ doesn't load

### ISSUE THREAD

**Issue by strugee** [osmc/website#7]
The HTTP version of the `www` subdomain properly redirects to the apex, but the HTTPS version does not connect at all.

This is particularly a problem because `https://www.osmc.tv/` is listed in `/etc/os-release`.

**Comment by tomdoyle87** [comment]
Hi, 

@samnazarko being as the site redirects to https://osmc.tv wouldn't be better update os-release to:

HOME_URL="https://osmc.tv"
SUPPORT_URL="https://osmc.tv"
BUG_REPORT_URL="https://osmc.tv"

Not that the issue shouldn't be fixed. (This is just a guess), I think nginx just needs the ssl server entry updating:

server {
  listen 443 ssl;

  server_name osmc.tv www.osmc.tv ;

Then get let's encrypt to issue a wildcard for osmc.tv. Or you get another cert just for www.osmc.tv, then create a new server entry for www & 443. 

Thanks Tom.

**Comment by samnazarko** [comment]
This issue is now solved, but I've also updated /etc/os-release to not use www.
Thanks for the report.
